version: '3.7'
services:
  # service1:
  #   image: gin-telemetry-example-server
  #   build: .
  #   environment:
  #     - EXTERNAL_SERVICE_URL=http://service2:7000
  #     - JAEGER_URL=http://jaeger:14268
  #     - SERVICE_NAME=SERVICE1
  #   ports:
  #     - "7000:7000"
  # service2:
  #   image: gin-telemetry-example-server
  #   environment:
  #     - JAEGER_URL=http://jaeger:14268
  #     - SERVICE_NAME=SERVICE2

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
